systems:
  - id: 3cea-amvic
    name: 3CEA (Amvic)
    airtableId: appsOHJyDxhPrHyxc
  - id: mobble
    name: Inhout Mobble
    airtableId: app25JFkKVKKEt5io
  - id: swift
    name: WikiHouse Swift
    airtableId: appGlzQcCZpDNRFsE
  - id: holz100
    name: HOLZ100
    airtableId: appzG3plVRqgH6c5f
  - id: skylark
    name: WikiHouse Skylark
    airtableId: app7fME5xo63IoGGI
